apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: justbooks
  namespace: justbooks
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: justbooks
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60